os: osx
osx_image: xcode10.1
branches:
  only:
    - master
language: swift
xcode_project: LolayInvestigo.xcodeproj
xcode_scheme: LolayInvestigo
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
xcode_sdk: iphonesimulator12.1

