os: osx
osx_image: xcode11.5
branches:
  only:
    - master
language: swift
xcode_workspace: LolayInvestigo.xcworkspace
xcode_scheme: LolayInvestigo
xcode_destination: platform=iOS Simulator,OS=13.5,name=iPhone Xs
xcode_sdk: iphonesimulator13.5
