name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-13

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE
    - name: Checkout
      uses: actions/checkout@v2
    - name: Xcode Select
      run: sudo xcode-select -switch /Applications/Xcode_15.0.1.app
    - name: Xcode Versions
      run: xcodebuild -version -sdk
    - name: Build and Test
      run: xcodebuild -scheme LolayInvestigo -sdk iphonesimulator17.0 -destination "platform=iOS Simulator,OS=17.0.1,name=iPhone 15" clean build test | xcpretty
