name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: xcode-27

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE
    - name: Checkout
      uses: actions/checkout@v7
    - name: Xcode Select
      run: sudo xcode-select -switch /Applications/Xcode_27.0.app
    - name: Xcode Versions
      run: xcodebuild -version -sdk
    - name: Build and Test
      run: set -o pipefail && xcodebuild -scheme LolayInvestigo -sdk iphonesimulator27.0 -destination "platform=iOS Simulator,OS=27.0,name=iPhone 17" clean build test | xcbeautify
